[env]
TERM = "xterm-256color"

[general]
import = ["themes/noctalia.toml"]

[window]
padding = { x = 12, y = 12 }
opacity = 0.95

[font]
size = 16
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
