[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[window]
padding = { x = 12, y = 12 }
opacity = 0.8

[font]
size = 20
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
