[colors.primary]
background = '#11131c'
foreground = '#e2e1ef'
 
[colors.cursor]
text = '#e2e1ef'
cursor = '#c3c5dd' 
 
[colors.vi_mode_cursor]
text = '#11131c'
cursor = '#64d3ff' 
 
[colors.search.matches]
foreground = '#434659' 
background = '#b9c3ff' 
 
[colors.search.focused_match]
foreground = '#434659' 
background = '#64d3ff' 
 
[colors.footer_bar]
foreground = '#434659' 
background = '#e2e1ef' 
 
[colors.hints.start]
foreground = '#434659' 
background = '#8ad0ef' 
 
[colors.hints.end]
foreground = '#434659' 
background = '#8ad0ef' 
 
[colors.selection]
text = '#11131c'
background = '#64d3ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#64d3ff' 
yellow = '#006783' 
blue = '#64d3ff' 
magenta = '#b9c3ff' 
cyan = '#8ad0ef' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 