[colors.primary]
background = '#121316'
foreground = '#e3e2e6'
 
[colors.cursor]
text = '#e3e2e6'
cursor = '#c4c6d0' 
 
[colors.vi_mode_cursor]
text = '#121316'
cursor = '#adc7ff' 
 
[colors.search.matches]
foreground = '#44474f' 
background = '#debcdf' 
 
[colors.search.focused_match]
foreground = '#44474f' 
background = '#adc7ff' 
 
[colors.footer_bar]
foreground = '#44474f' 
background = '#e3e2e6' 
 
[colors.hints.start]
foreground = '#44474f' 
background = '#bec6dc' 
 
[colors.hints.end]
foreground = '#44474f' 
background = '#bec6dc' 
 
[colors.selection]
text = '#121316'
background = '#adc7ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#adc7ff' 
yellow = '#305da8' 
blue = '#adc7ff' 
magenta = '#debcdf' 
cyan = '#bec6dc' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 